version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elasticsearch
    environment:    
    - "http.host=0.0.0.0"
    - "discovery.type=single-node"
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - /volumes/elk/elasticsearch/data/:/usr/share/elasticsearch/data/
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.2
    container_name: logstash
    environment:
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_URL: http://elasticsearch:9200
    command: logstash -f /usr/share/logstash/config/logstash.conf
    volumes:
      - /volumes/elk/logstash/config:/usr/share/logstash/config
    networks:
      - elk-network    
    depends_on:
      - elasticsearch     

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      SERVER_HOST: 0.0.0.0      
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
    - "5601:5601"
    links:
      - elasticsearch
    networks:
      - elk-network
    depends_on:
      - elasticsearch

networks: 
    elk-network:
      driver: bridge