version: '3.1'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 15432:80
    volumes:
      - /volumes/postgresql/pgadmin:/var/lib/pgadmin
    links:
      - postgres
    networks:
      - postgres-network

  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - /volumes/postgresql/data:/var/lib/postgresql/data    
    networks:
      - postgres-network

networks: 
    postgres-network:
      driver: bridge